In [17]:
import numpy as np
import pandas as pd

In [20]:
import pandas as pd
df = pd.read_csv("student_performance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group C,some college,free/reduced,completed,69.0,73.0,49.0
1,female,group E,some high school,free/reduced,none,61.0,47.0,99.0
2,female,group E,some high school,standard,none,76.0,62.0,100.0
3,male,group C,master's degree,free/reduced,none,30.0,95.0,94.0
4,male,group C,associate's degree,free/reduced,none,56.0,99.0,54.0
...,...,...,...,...,...,...,...,...
995,male,group B,bachelor's degree,standard,completed,59.0,84.0,75.0
996,male,group D,high school,standard,completed,78.0,62.0,66.0
997,male,group D,some college,free/reduced,completed,32.0,94.0,47.0
998,male,group A,some high school,standard,none,42.0,64.0,62.0
999,male,group A,associate's degree,standard,none,31.0,60.0,79.0

In [91]:
df.head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score,avg score
0,female,group C,some college,free/reduced,completed,69.0,73.0,49.0,191.0,187.300403
1,female,group E,some high school,free/reduced,none,61.0,47.0,99.0,207.0,187.300403
2,female,group E,some high school,standard,none,76.0,62.0,100.0,238.0,187.300403
3,male,group C,master's degree,free/reduced,none,30.0,95.0,94.0,219.0,187.300403
4,male,group C,associate's degree,free/reduced,none,56.0,99.0,54.0,209.0,187.300403

In [21]:
df.shape

(1000, 8)

In [92]:
df.tail(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score,avg score
995,male,group B,bachelor's degree,standard,completed,59.0,84.0,75.0,218.0,187.300403
996,male,group D,high school,standard,completed,78.0,62.0,66.0,206.0,187.300403
997,male,group D,some college,free/reduced,completed,32.0,94.0,47.0,173.0,187.300403
998,male,group A,some high school,standard,none,42.0,64.0,62.0,168.0,187.300403
999,male,group A,associate's degree,standard,none,31.0,60.0,79.0,170.0,187.300403

In [89]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'total_score', 'avg score'],
      dtype='object')

In [27]:
df.dtypes

gender                          object
race/ethnicity                  object
parental level of education     object
lunch                           object
test preparation course         object
math score                     float64
reading score                  float64
writing score                  float64
dtype: object

In [32]:
df.isnull().sum()

gender                         3
race/ethnicity                 3
parental level of education    4
lunch                          2
test preparation course        3
math score                     2
reading score                  3
writing score                  3
dtype: int64

In [39]:
df[["math score","reading score"]]

     math score  reading score
0          69.0           73.0
1          61.0           47.0
2          76.0           62.0
3          30.0           95.0
4          56.0           99.0
..          ...            ...
995        59.0           84.0
996        78.0           62.0
997        32.0           94.0
998        42.0           64.0
999        31.0           60.0

[1000 rows x 2 columns]

In [45]:
print(df["gender"].value_counts())

gender
male      506
female    491
Name: count, dtype: int64

In [46]:
print(df["lunch"].unique())

['free/reduced' 'standard' nan]

In [49]:
(df[df["math score"] > 80])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
11,male,group E,bachelor's degree,standard,completed,86.0,85.0,74.0
13,female,group D,some college,free/reduced,none,81.0,90.0,64.0
15,female,group C,associate's degree,standard,completed,97.0,71.0,97.0
18,male,group C,some college,standard,none,82.0,69.0,81.0
21,male,group A,associate's degree,free/reduced,completed,90.0,31.0,69.0
...,...,...,...,...,...,...,...,...
969,female,group D,some college,standard,none,82.0,36.0,40.0
972,male,group D,some high school,free/reduced,completed,81.0,64.0,50.0
973,male,group E,master's degree,free/reduced,none,99.0,51.0,70.0
977,female,group A,some high school,standard,none,92.0,56.0,91.0
979,female,group B,some college,standard,completed,99.0,63.0,30.0

In [51]:
print(df["test preparation course"].unique())

['completed' 'none' nan]

In [54]:
print(df[df["test preparation course"]=='completed'])

     gender race/ethnicity parental level of education         lunch  \
0    female        group C                some college  free/reduced
6    female        group E          associate's degree  free/reduced
7      male        group D          associate's degree  free/reduced
10   female        group C                 high school  free/reduced
11     male        group E           bachelor's degree      standard
..      ...            ...                         ...           ...
992    male        group E             master's degree      standard
994    male        group D             master's degree      standard
995    male        group B           bachelor's degree      standard
996    male        group D                 high school      standard
997    male        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                 completed        69.0           73.0           49.0
6                 completed        47.0           43.0           34.0
7                 completed        43.0           66.0           57.0
10                completed        78.0           90.0           36.0
11                completed        86.0           85.0           74.0
..                      ...         ...            ...            ...
992               completed        51.0           68.0           51.0
994               completed        69.0           56.0           93.0
995               completed        59.0           84.0           75.0
996               completed        78.0           62.0           66.0
997               completed        32.0           94.0           47.0

[357 rows x 8 columns]

In [84]:
print(df[(df["gender"] == "female") & (df["reading score"] > 80) ])

     gender race/ethnicity parental level of education         lunch  \
10   female        group C                 high school  free/reduced
13   female        group D                some college  free/reduced
30   female        group C           bachelor's degree      standard
48   female        group C            some high school  free/reduced
59   female        group A           bachelor's degree      standard
..      ...            ...                         ...           ...
960  female        group C            some high school      standard
967  female        group B                 high school      standard
974  female        group C                 high school      standard
983  female        group B                 high school      standard
990  female        group C            some high school  free/reduced

    test preparation course  math score  reading score  writing score  \
10                completed        78.0           90.0           36.0
13                     none        81.0           90.0           64.0
30                completed        61.0          100.0           43.0
48                     none        82.0           94.0           56.0
59                     none        25.0           93.0           77.0
..                      ...         ...            ...            ...
960                    none        35.0           96.0           74.0
967                    none        86.0           93.0           78.0
974                    none        52.0          100.0           33.0
983               completed        58.0           83.0           54.0
990                    none        70.0           86.0           71.0

     total_score   avg score
10         204.0  187.300403
13         235.0  187.300403
30         204.0  187.300403
48         232.0  187.300403
59         195.0  187.300403
..           ...         ...
960        205.0  187.300403
967        257.0  187.300403
974        185.0  187.300403
983        195.0  187.300403
990        227.0  187.300403

[128 rows x 10 columns]

In [90]:
print(df.groupby("gender")["reading score"].mean())

gender
female    63.353783
male      62.413861
Name: reading score, dtype: float64

In [66]:
print(df.groupby("race/ethnicity").size())

race/ethnicity
group A    212
group B    199
group C    206
group D    169
group E    211
dtype: int64

In [68]:
print(df.groupby("gender")["reading score"].mean())

gender
female    63.353783
male      62.413861
Name: reading score, dtype: float64

In [72]:
print(df.sort_values("math score",ascending = False).head(10))

     gender race/ethnicity parental level of education         lunch  \
801  female        group A            some high school      standard
126    male        group B          associate's degree  free/reduced
433    male        group E          associate's degree  free/reduced
878    male        group A                 high school  free/reduced
827    male        group E             master's degree      standard
642  female        group A          associate's degree      standard
283  female        group C            some high school  free/reduced
495  female        group A           bachelor's degree      standard
130    male        group B            some high school      standard
915    male        group A                 high school      standard

    test preparation course  math score  reading score  writing score
801               completed       100.0           29.0           69.0
126                    none       100.0           45.0           87.0
433               completed       100.0           36.0           46.0
878                    none       100.0           88.0           96.0
827                    none       100.0           26.0           75.0
642               completed       100.0           78.0           77.0
283                    none       100.0           28.0           57.0
495               completed       100.0           48.0           81.0
130                    none       100.0           87.0           62.0
915               completed       100.0           61.0           95.0

In [73]:
df["total_score"]=df["math score"]+df["reading score"]+df["writing score"]

In [74]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score
0,female,group C,some college,free/reduced,completed,69.0,73.0,49.0,191.0
1,female,group E,some high school,free/reduced,none,61.0,47.0,99.0,207.0
2,female,group E,some high school,standard,none,76.0,62.0,100.0,238.0
3,male,group C,master's degree,free/reduced,none,30.0,95.0,94.0,219.0
4,male,group C,associate's degree,free/reduced,none,56.0,99.0,54.0,209.0
...,...,...,...,...,...,...,...,...,...
995,male,group B,bachelor's degree,standard,completed,59.0,84.0,75.0,218.0
996,male,group D,high school,standard,completed,78.0,62.0,66.0,206.0
997,male,group D,some college,free/reduced,completed,32.0,94.0,47.0,173.0
998,male,group A,some high school,standard,none,42.0,64.0,62.0,168.0
999,male,group A,associate's degree,standard,none,31.0,60.0,79.0,170.0

In [78]:
df["avg score"] = df["total_score"].mean()
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score,avg score
0,female,group C,some college,free/reduced,completed,69.0,73.0,49.0,191.0,187.300403
1,female,group E,some high school,free/reduced,none,61.0,47.0,99.0,207.0,187.300403
2,female,group E,some high school,standard,none,76.0,62.0,100.0,238.0,187.300403
3,male,group C,master's degree,free/reduced,none,30.0,95.0,94.0,219.0,187.300403
4,male,group C,associate's degree,free/reduced,none,56.0,99.0,54.0,209.0,187.300403
...,...,...,...,...,...,...,...,...,...,...
995,male,group B,bachelor's degree,standard,completed,59.0,84.0,75.0,218.0,187.300403
996,male,group D,high school,standard,completed,78.0,62.0,66.0,206.0,187.300403
997,male,group D,some college,free/reduced,completed,32.0,94.0,47.0,173.0,187.300403
998,male,group A,some high school,standard,none,42.0,64.0,62.0,168.0,187.300403
999,male,group A,associate's degree,standard,none,31.0,60.0,79.0,170.0,187.300403